### PR TITLE
Bearer token support for User Authentication

### PR DESCRIPTION
**Pull request by erikn69**
This PR helps when you use tokens like in APIs

### Purpose
Pusher launched a feature that allows their users to enable authentication for connections, alongside the channel authorizations: https://pusher.com/docs/channels/using_channels/user-authentication/
It's a feature that will make sure that anyone connecting to the websockets should be an authenticated user within the app. 

### Example
**Before:**
```ts
{
        broadcaster: 'pusher',
        auth: {
            headers: {
                Authorization: "Bearer " + TOKEN_STRING
            },
        },
        userAuthentication: {
            headers: {
                Authorization: "Bearer " + TOKEN_STRING
            },
        },

        host: HOST,
        key: APP_KEY
    }
```
**After:**
```ts
{       
        broadcaster: 'pusher',
        bearerToken: TOKEN_STRING,
        host: HOST,
        key: APP_KEY
}
```

## Context
* PR: [9.x] User authentication for Pusher framework#42531
* `signin()` method: https://pusher.com/docs/channels/using_channels/user-authentication/#sign-in

Same as `CSRF-TOKEN`
https://github.com/laravel/echo/blob/d41094a794edb85e87ee11fd69328ddf5b7e4091/src/connector/connector.ts#L44-L47

### CODE REVIEW

**Comment by taylorotwell** [comment]
It feels weird to me this is "instead of" a CSRF token in your else check?

**Comment by erikn69** [comment]
I did change it

**Comment by taylorotwell** [comment]
I'm sorry - I just don't understand this change and the original PR was such that it was obviously not tested in a real app. Not comfortable merging this right now.

**Comment by erikn69** [comment]
@taylorotwell If i upload a test on a real app will change the things??

**Comment by parallels999** [comment]
@rennokki ping :)

**Comment by parallels999** [comment]
@taylorotwell `Authorization: "Bearer *********"` always was used
https://github.com/laravel/echo/issues/189#issuecomment-1151122757
https://github.com/laravel/echo/issues/26#issuecomment-313898800
https://github.com/laravel/echo/issues/26#issuecomment-320472148
https://github.com/laravel/echo/issues/26#issuecomment-370832818
https://github.com/laravel/echo/issues/26#issuecomment-394170044
https://github.com/laravel/echo/issues/282#issuecomment-670778544
https://github.com/laravel/echo/issues/219#issue-396205561

**Comment by angeljqv** [comment]
This helps when
```php
Broadcast::routes(["middleware" => ['auth:api',/*'auth:sanctum',*/]]);
```

**Comment by parallels999** [comment]
@rennokki ping :)

**Comment by parallels999** [comment]
@rennokki ping :)

**Comment by parallels999** [comment]
@rennokki ping :)

**Pull request closed without merging**
