### PR TITLE
[SocketIO] Implement whisper for SocketIO

### PR DESCRIPTION
**Pull request by barryvdh**
Implement 'whisper' functionality for SocketIO, based on Pusher.
 
 - Move listener to basic channel
 - Create private SocketIO channel with whisper method
 - Extend Presence channel from private channel

cc @tlaverdure for server implementation, serverside PR: https://github.com/tlaverdure/laravel-echo-server/pull/100

### CODE REVIEW

**Comment by barryvdh** [comment]
Note that this was just an implementation to see if it works correctly, we need to add verification for the client. Just check if the socketId exists in `this.io.sockets.adapter.rooms`?

**Comment by barryvdh** [comment]
Updated event name to be more clear: `client event`

**Comment by taylorotwell** [comment]
If it has to hit the server is it really a counterpart to the Pusher version?

**Comment by taylorotwell** [comment]
I guess it doesn't have to hit the Laravel application?

**Comment by barryvdh** [comment]
It doesn't hit the Laravel server I think, it emits a message to the Node server and the broadcasts is to the other clients. See https://github.com/tlaverdure/laravel-echo-server/blob/f1ce0fca5c7198af9d9befc98483fd7488d9adfc/src/channels/channel.ts#L69-L81

**Comment by barryvdh** [comment]
Or where do you see it hitting Laravel?

**Comment by tlaverdure** [comment]
Looks good to me 👍

**Comment by taylorotwell** [comment]
Thanks :heart:

**Comment by zdenektopic** [comment]
Is there also something at actually sends events from client to laravel?
Example: Chat application
- users sends message over socket.io
- node hits laravel
- laravel receives event with user and channel info

I guess its the same as making HTTP request directly to laravel, but can you do that simply with context of the user AND CHANNEL?

**Comment by barryvdh** [comment]
What would be the benefit over a plain XHR request to Laravel directly?

**Comment by zdenektopic** [comment]
You are right, there is not actual benefit. It just makes it possible to wrap it all in one communication layer.
Anyway, is it possible to send XHR that resolves the channel and user context in laravel?

Actually the Echo JS client could be able to emit events back to Laravel directly with XHR.

**Pull request merged**
