### PR TITLE
Added listen methods to presence channels and interface - prevent Angular build errors

### PR DESCRIPTION
**Pull request by Mathem8tic**
@driesvints this is most likely not the correct solution, but it does prevent the errors which are stopping the build from succeeding when using Angular CLI.  You will see I just added the listen method to the various PresenceChannels.

I hope this helps!

### CODE REVIEW

**Comment by taylorotwell** [comment]
If it's most likely not the correct solution let's not do it. 😬

**Comment by Mathem8tic** [comment]
Sorry, it works.  I just don't know if it is as clean as your standards.  I wanted @driesvints to take a look since he requested a PR.

Cheers.

**Comment by driesvints** [comment]
I need to be able to reproduce the issue first. Please provide a repo that reproduces it.

**Comment by driesvints** [comment]
@Mathem8tic ah just saw in the issue that you did. I'll try to have a look soon.

**Comment by sebastiandedeyne** [comment]
@Mathem8tic Why don't you consider this to be the right solution?

**Comment by Mathem8tic** [comment]
I think it might be correct.  I just assumed those methods were left out
for a reason that I was unaware of.  I can confirm that the solution works
nicely for my project.

Feel free to pull it in if you are satisfied with the additions.

Take care.

**Comment by driesvints** [comment]
Okay, re-opening then.

**Comment by taylorotwell** [comment]
Can someone let me know what issue we are attempting to fix?

**Comment by Mathem8tic** [comment]
#239

**Comment by taylorotwell** [comment]
This doesn't maky any sense. Pusher presence channel *ALREADY* extends PusherChannel which already has a `listen` method with an implementation. Surely overriding that with a new `listen` method which just does `return this` doesn't seem like the best idea and will break applications?

**Comment by driesvints** [comment]
I really don't know sorry. I can reproduce this but I have too limited knowledge of typescript or javascript to know what the best solution is.

**Comment by mengyang1229** [comment]
@Mathem8tic @taylorotwell @driesvints @sebastiandedeyne @ellisio 

Here is my solution and hope it can help you. Thank you.

[https://github.com/laravel/echo/issues/239#issuecomment-550114637](https://github.com/laravel/echo/issues/239#issuecomment-550114637)

**Comment by johnpaulmedina** [comment]
So I found that there isn't a bug or an issue with the interface at all with the PresenceChannel.

Just assign as the type for your LaravelEchoChannel ng-cli wont throw any errors.
```es6
  private echo: Echo;
  private LaravelEchoChannel: any;

  LaravelEchoChannel = echo.join(channel)
     .here((users: any) => {
       log.debug('[Presence][Channel]', users);
     })
     .joining((user: any) => {
       log.debug('joining', user.name);
     })
     .leaving((user: any) => {
       log.debug('leaving', user.name);
     });

  LaravelEchoChannel
    .listen('.event', (event: string) => {
       log.debug('event');
    });
```

This seems more of a ng-cli ts config issue.

**Pull request closed without merging**
