### PR TITLE
feat: add echo options type to improve DX & use rollup to ship types

### PR DESCRIPTION
**Pull request by dammy001**
… files

The bundle size has reduced also.

### CODE REVIEW

**Comment by nandi95** [comment]
This is similar to https://github.com/laravel/echo/pull/356 😁

**Comment by jessarcher** [comment]
Thanks for the PR!

I'm all for adding the type definitions and eliminating as many `any` as possible!

There are quite a few additional opinionated changes in this PR, and some bundling changes that have me concerned, given how often stuff like this has broken peoples' apps.

For example, the IIFE changes have me worried that this PR reintroduces the issue solved in #344.

**Comment by taylorotwell** [comment]
Mark as ready for review when ready for me to review again please.

**Comment by dammy001** [comment]
> Thanks for the PR!
> 
> I'm all for adding the type definitions and eliminating as many `any` as possible!
> 
> There are quite a few additional opinionated changes in this PR, and some bundling changes that have me concerned, given how often stuff like this has broken peoples' apps.
> 
> For example, the IIFE changes have me worried that this PR reintroduces the issue solved in #344.

@jessarcher i get your point about the IIFE breaking change, I'll revert the declaration part.

**Comment by dammy001** [comment]
@jessarcher please take a look at this again. potential IIFE issue has been reverted

**Comment by jessarcher** [comment]
@dammy001 There's still an awful lot going on in this PR unrelated to the PR title.

Is it possible to *just* add the options types without installing extra packages and reconfiguring the entire build process and module set-up?

**Comment by driesvints** [comment]
@dammy001 have you seen Jess' questions? Are you still working on this?

**Comment by dammy001** [comment]
@driesvints I'll work on the changes today.

**Comment by driesvints** [comment]
@dammy001 feel free to resend this once you have more time

**Pull request closed without merging**
