### PR TITLE
Removed unnecessary check

### PR DESCRIPTION
**Pull request by dzava**
Goes with #59.

### CODE REVIEW

**Comment by tlaverdure** [comment]
`namespace` is always part of the default options so I don't believe this PR would actually fix anything. If you don't want to use a namespace you will need to set the option to false. 

This also doesn't appear to be published to npm yet, which means it hasn't been made available.

**Comment by dzava** [comment]
You are correct, the check should be removed altogether.

**Comment by dzava** [comment]
Actually we should either change the condition to check for an empty string or change the default namespace in connector.ts.

**Comment by taylorotwell** [comment]
Needs actual explanation of what we're trying to do here. Please re-open a PR with a proper description and explanation if we need to fix something.

**Pull request closed without merging**
