### PR TITLE
Pass full options to socketIO

### LINKED ISSUE #80: Ability to pass on option "path" to socket io connection
Please allow passing on path in options to socket io connector.

It is not possible to use different route than "/" because anything after "/" is treated as namespace.

e.g.
var echo = new Echo({
    broadcaster: 'socket.io',
    host: 'http://localhost',
    path: '/myapp/socket.io/'
});

This path should be used while creating io socket as:

this.socket = io(this.options.host, {path: this.options.path});

Thanks very much in advance.

### PR DESCRIPTION
**Pull request by barryvdh**
Pass entire options to the options parameter to allow customisation, similar to Pusher.
Fixes #80

### CODE REVIEW

**Comment by taylorotwell** [comment]
Does still work if someone specifies options socket.io doesn't support?

**Comment by barryvdh** [comment]
I think so. `host` and `broadcaster` are already options that don't exist in SocketIO. Only problem could be if they DO exist, because of conflicts..

**Comment by taylorotwell** [comment]
Did you test it?

**Comment by barryvdh** [comment]
Yes I tested that the options are passed to the io instance, and that it still works.

**Pull request merged**
