### PR TITLE
Fixes Not receiving notifications

### PR DESCRIPTION
**Pull request by matrunchyk**
Fixes https://github.com/laravel/echo/issues/135 and https://github.com/laravel/echo/issues/137

### CODE REVIEW

**Comment by taylorotwell** [comment]
Why does this keep breaking?

**Comment by taylorotwell** [comment]
I'm so tired of going back and forth on this. Is anyone testing this with an actual application? Are we just shooting in the dark hoping shit works?

**Comment by taylorotwell** [comment]
Ping @ellisio

**Comment by taylorotwell** [comment]
I'm going to have to build a little demo Echo app myself today to really make sure all this shit is working.

**Comment by matrunchyk** [comment]
@taylorotwell Well it should work properly with `presence`, `private` wrappers as well as with raw `listen` method. @ellisio please let us know does it work for your case as well.

**Comment by taylorotwell** [comment]
Let's stop saying "it should work", etc. Either let's make sure it works or stop submitting PRs.

**Comment by taylorotwell** [comment]
Ping @themsaid, we need a test application that tests every Echo situation in the documentation.

**Comment by ellisio** [comment]
I'll take a look at the thread this afternoon. Busy conducting interviews this AM.

**Comment by ellisio** [comment]
Just quickly looking over this code, this fix would break dot syntax. By replacing all dots with `\` you'd cause the developer to do `.listen('server\\created')` and not `.listen('server.created')`.

**Comment by tlaverdure** [comment]
I'm going to take a look at this as well.

**Comment by themsaid** [comment]
@taylorotwell on it

**Comment by ellisio** [comment]
Okay, so I just dug into the core of Echo and these are the following patterns we need to support:

- Notifications: `.Illuminate.Notifications.Events.BroadcastNotificationCreated` -> `Illuminate\\Notifications\\Events\\BroadcastNotificationCreated`
- App\Events: `Server.Created` -> `App\\Events\\Server\\Created`
- App\Events: `Server\\Created` -> `App\\Events\\Server\\Created`
- FooBar\Events: `.FooBar.Events.MyEvent` -> `FooBar\\Events\\MyEvent`
- FooBar\Events: `\\FooBar\\Events\\MyEvent` -> `FooBar\\Events\\MyEvent`
- Dotsyntax: `.server.created` => `server.created`

I'm poking around the core to see where the disconnect is and why the above can't work. Obviously it's not just the Formatter causing issues with Notifications breaking with `1.3.1`'s implementation of the Formatter.

**Comment by taylorotwell** [comment]
The format is really pretty simple. If it starts with a `.` then you just remove the dot or slash and use the name as given. Nothing else should be done to the name. `.` should not be replaced with `\` if it starts with a leading `.`. So, your "notifications" example should not be translated that way.

If the name does not start with a `.`, you prepend the namespace onto it, and all `.` in the name are replaced by `\`.

Those are the only two situations I ever intended to support and they will cover any case necessary.

**Comment by taylorotwell** [comment]
I tried to summarize things as best as I can above.

**Comment by ellisio** [comment]
@taylorotwell  Exactly, that is the clash and what I'm seeing when trying to dig into the core. I think the leading `\` was to allow developers to have events in different Namespaces. BUT that can be resolved by doing:

`.FooBar\\Events\\`

So in all honesty, I'm confused as to what is even broken. By this logic, when `.Illuminate.Notifications.Events.BroadcastNotificationCreated` is passed into the formatter, in `1.3.1` this will return `Illuminate.Notifications.Events.BroadcastNotificationCreated` as expected. So why are people's notifications breaking? Especially since that is how Laravel broadcasts events in that manner. 

My bet is they implemented `receivesBroadcastNotificationsOn` and that method is returning something that is causing Echo to spew on itself.

**Comment by ellisio** [comment]
@taylorotwell  Exactly, that is the clash and what I'm seeing when trying to dig into the core. I think the leading `\` was to allow developers to have events in different Namespaces. BUT that can be resolved by doing:

`.FooBar\\Events\\`

So in all honesty, I'm confused as to what is even broken. By this logic, when `.Illuminate.Notifications.Events.BroadcastNotificationCreated` is passed into the formatter, in `1.3.1` this will return `Illuminate.Notifications.Events.BroadcastNotificationCreated` as expected. So why are people's notifications breaking? Especially since that is how Laravel broadcasts events in that manner. 

My bet is they implemented `receivesBroadcastNotificationsOn` and that method is returning something that is causing Echo to spew on itself.

**Comment by ellisio** [comment]
@taylorotwell as expected, looking at #137, they're doing:

```
.listen('.Illuminate\\Notifications\\Events\\BroadcastNotificationCreated')
```

When it should be:

```
.listen('.Illuminate.Notifications.Events.BroadcastNotificationCreated')
```

Where in the documentation are people finding this implementation? I can't find it anywhere...

**Comment by taylorotwell** [comment]
@ellisio But `Illuminate.Notifications.Events.BroadcastNotificationCreated` isn't how the event is broadcast? It is broadcast from the backend as: `Illuminate\Notifications.Events\BroadcastNotificationCreated`.

Am I correct?

**Comment by taylorotwell** [comment]
From my brief reading of the EventFormatter class currently on master branch of Echo, the implementation is correct:

screen shot 2017-07-31 at 12 09 39 pm

Removes first character only if leading `.` or leading `\` and immediately returns with no other changes.

Else, prepends namespace if we have one.

Finally, translates dots to slash.

**Comment by ellisio** [comment]
I honestly don't even see how that class is being broadcasted in the first place:

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Notifications/Events/BroadcastNotificationCreated.php#L84-L92

That is telling me that it'll be `App.User.1`. I'm so confused as to where that `Illuminate.Notifications.Events.BroadcastNotificationCreated` is even coming from, or why it is there. Is that from a 5.0, 5.1, 5.2, or 5.3 implementation?

**Comment by matrunchyk** [comment]
This is what I see in Laravel Echo Server logs as an example:
```
Channel: private-users.afa3b365-3f01-4f85-a632-e3588c11f031
Event: Illuminate\Notifications\Events\BroadcastNotificationCreated
CHANNEL private-users.afa3b365-3f01-4f85-a632-e3588c11f031
```

Not sure about Pusher.
So as I understand, notifications are broadcasted `Illuminate\Notifications\Events\BroadcastNotificationCreated`.

**Comment by ellisio** [comment]
@matrunchyk How are you triggering that event in Laravel? Sorry if this seems like a basic question, just trying to fall into the rabbit hole so I can step my way back out.

**Comment by ellisio** [comment]
Alright, so it's `Illuminate\Events\Dispatcher` formatting this event payload. So what happens is Pusher, Redis, etc. are all broadcasting to the `App.User.1` channel with the event `Illuminate\Notifications\Events\BroadcastNotificationCreated`.

So it looks like the fix I have in 1.3.1 is valid, and then we need to change [this method](\Notifications\Events\BroadcastNotificationCreated) to this:

```
    notification(callback: Function): Channel {
        return this.listen('.Illuminate\\Notifications\\Events\\BroadcastNotificationCreated', callback);
    }
```

**Comment by matrunchyk** [comment]
I do it by `$user->notify(new PostCreated($post));`

And how I catch it on the frontend:
```
this.echo = new Echo({
    broadcaster: 'socket.io',
    key: this.config.key,
    host: `${this.config.host}:${this.config.port}`,
    encrypted: true,
});
this.echo.private('users.afa3b365-3f01-4f85-a632-e3588c11f031').notification((notification) => {
    // 
});
```

**Comment by taylorotwell** [comment]
Andrew is correct that only notification method in Echo needs to change to use \
		

		
	





On Mon, Jul 31, 2017 at 12:32 PM -0500, "Andrew Ellis" <notifications@github.com> wrote:












Alright, so it's Illuminate\Events\Dispatcher formatting this event payload. So what happens is Pusher, Redis, etc. are all broadcasting to the App.User.1 channel with the event Illuminate\Notifications\Events\BroadcastNotificationCreated.


So it looks like the fix I have in 1.3.1 is valid, and then we need to change this method to this:
    notification(callback: Function): Channel {
        return this.listen('.Illuminate\\Notifications\\Events\\BroadcastNotificationCreated', callback);
    }

**Pull request closed without merging**
