### PR TITLE
 General maintenance, code styling, and add stopListening() for socket.io

### PR DESCRIPTION
**Pull request by tlaverdure**
Hey just wanted to provide some updates. Shouldn't be any errors or breaking changes.

* Updated npm dependencies to clear some vulnerabilities
* Use `npm run build` instead of `npm run compile` before publish to run compile and declaration scripts before publishing
* Add declaration files to the distribution for typescript users (addresses https://github.com/laravel/echo/issues/84)
* Removed doc blocks where type definitions were in place. Seems redundant to have both now.
* Add `stopListening()` to socket.io channel (closes https://github.com/laravel/echo/issues/51)

### CODE REVIEW

**Comment by taylorotwell** [comment]
Published 1.5.0.

**Comment by yoyo930021** [comment]
m... package is breaking change about module standard.
CommonJS -> ES6
if  use `require` to add this lib, will break.

**Comment by tlaverdure** [comment]
How are you using this package? I know most people in their laravel apps use mix to bundle with webpack.

**Comment by udanpe** [comment]
@tlaverdure Most people it's how much? Other not people?

**Pull request merged**
