### PR TITLE
Add unlisten to pusher-channel

### PR DESCRIPTION
**Pull request by defraz**
Adds functionality to unlisten to events on a channel without unsubscribing from the entire channel.

### CODE REVIEW

**Comment by taylorotwell** [comment]
The pusher documentation examples always show passing the original callback.

**Comment by defraz** [comment]
I'll add the ability to remove a specific handler. I was following the second option on unbind that allows you to remove all handlers.

**Comment by taylorotwell** [comment]
Is that documented somewhere I can see?

**Comment by defraz** [comment]
Yeah. https://github.com/pusher/pusher-js#bind-and-unbind

**Comment by taylorotwell** [comment]
Gotcha, OK this is fine then

**Comment by taylorotwell** [comment]
Published echo 1.2.4

**Pull request merged**
